window.MathEditor = window.MathEditor || {};

window.MathEditor.toolbarData = [
  {
    id: "greek",
    label: "ギリシャ文字",
    icon: "α",
    buttons: [
      { label: "α", latex: "\\alpha", tooltip: "アルファ (alpha)" },
      { label: "β", latex: "\\beta", tooltip: "ベータ (beta)" },
      { label: "γ", latex: "\\gamma", tooltip: "ガンマ (gamma)" },
      { label: "δ", latex: "\\delta", tooltip: "デルタ (delta)" },
      { label: "ε", latex: "\\epsilon", tooltip: "イプシロン (epsilon)" },
      { label: "ζ", latex: "\\zeta", tooltip: "ゼータ (zeta)" },
      { label: "η", latex: "\\eta", tooltip: "エータ (eta)" },
      { label: "θ", latex: "\\theta", tooltip: "シータ (theta)" },
      { label: "ι", latex: "\\iota", tooltip: "イオタ (iota)" },
      { label: "κ", latex: "\\kappa", tooltip: "カッパ (kappa)" },
      { label: "λ", latex: "\\lambda", tooltip: "ラムダ (lambda)" },
      { label: "μ", latex: "\\mu", tooltip: "ミュー (mu)" },
      { label: "ν", latex: "\\nu", tooltip: "ニュー (nu)" },
      { label: "ξ", latex: "\\xi", tooltip: "クシー (xi)" },
      { label: "π", latex: "\\pi", tooltip: "パイ (pi)" },
      { label: "ρ", latex: "\\rho", tooltip: "ロー (rho)" },
      { label: "σ", latex: "\\sigma", tooltip: "シグマ (sigma)" },
      { label: "τ", latex: "\\tau", tooltip: "タウ (tau)" },
      { label: "υ", latex: "\\upsilon", tooltip: "ウプシロン (upsilon)" },
      { label: "φ", latex: "\\phi", tooltip: "ファイ (phi)" },
      { label: "χ", latex: "\\chi", tooltip: "カイ (chi)" },
      { label: "ψ", latex: "\\psi", tooltip: "プサイ (psi)" },
      { label: "ω", latex: "\\omega", tooltip: "オメガ (omega)" },
      { label: "Γ", latex: "\\Gamma", tooltip: "ガンマ (大文字)" },
      { label: "Δ", latex: "\\Delta", tooltip: "デルタ (大文字)" },
      { label: "Θ", latex: "\\Theta", tooltip: "シータ (大文字)" },
      { label: "Λ", latex: "\\Lambda", tooltip: "ラムダ (大文字)" },
      { label: "Ξ", latex: "\\Xi", tooltip: "クシー (大文字)" },
      { label: "Π", latex: "\\Pi", tooltip: "パイ (大文字)" },
      { label: "Σ", latex: "\\Sigma", tooltip: "シグマ (大文字)" },
      { label: "Φ", latex: "\\Phi", tooltip: "ファイ (大文字)" },
      { label: "Ψ", latex: "\\Psi", tooltip: "プサイ (大文字)" },
      { label: "Ω", latex: "\\Omega", tooltip: "オメガ (大文字)" }
    ]
  },
  {
    id: "operators",
    label: "演算子",
    icon: "±",
    buttons: [
      { label: "+", latex: "+", tooltip: "足す" },
      { label: "−", latex: "-", tooltip: "引く" },
      { label: "×", latex: "\\times", tooltip: "掛ける" },
      { label: "÷", latex: "\\div", tooltip: "割る" },
      { label: "±", latex: "\\pm", tooltip: "プラスマイナス" },
      { label: "∓", latex: "\\mp", tooltip: "マイナスプラス" },
      { label: "·", latex: "\\cdot", tooltip: "ドット積" },
      { label: "∗", latex: "\\ast", tooltip: "アスタリスク" },
      { label: "⊕", latex: "\\oplus", tooltip: "直和" },
      { label: "⊗", latex: "\\otimes", tooltip: "テンソル積" },
      { label: "∘", latex: "\\circ", tooltip: "合成" }
    ]
  },
  {
    id: "relations",
    label: "関係",
    icon: "≤",
    buttons: [
      { label: "=", latex: "=", tooltip: "等号" },
      { label: "≠", latex: "\\neq", tooltip: "等しくない" },
      { label: "<", latex: "<", tooltip: "小なり" },
      { label: ">", latex: ">", tooltip: "大なり" },
      { label: "≤", latex: "\\leq", tooltip: "以下" },
      { label: "≥", latex: "\\geq", tooltip: "以上" },
      { label: "≪", latex: "\\ll", tooltip: "非常に小さい" },
      { label: "≫", latex: "\\gg", tooltip: "非常に大きい" },
      { label: "≈", latex: "\\approx", tooltip: "近似" },
      { label: "≡", latex: "\\equiv", tooltip: "合同" },
      { label: "∼", latex: "\\sim", tooltip: "類似" },
      { label: "≃", latex: "\\simeq", tooltip: "漸近的に等しい" },
      { label: "∝", latex: "\\propto", tooltip: "比例" },
      { label: "⊂", latex: "\\subset", tooltip: "部分集合" },
      { label: "⊃", latex: "\\supset", tooltip: "上位集合" },
      { label: "⊆", latex: "\\subseteq", tooltip: "部分集合 (等号含む)" },
      { label: "⊇", latex: "\\supseteq", tooltip: "上位集合 (等号含む)" },
      { label: "∈", latex: "\\in", tooltip: "属する" },
      { label: "∉", latex: "\\notin", tooltip: "属さない" },
      { label: "∋", latex: "\\ni", tooltip: "含む" }
    ]
  },
  {
    id: "structures",
    label: "構造",
    icon: "√",
    buttons: [
      { label: "x²", latex: "^{}", tooltip: "上付き文字", cursorOffset: -1 },
      { label: "xₙ", latex: "_{}", tooltip: "下付き文字", cursorOffset: -1 },
      { label: "x²ₙ", latex: "_{}^{}", tooltip: "下付き+上付き", cursorOffset: -4 },
      { label: "a/b", latex: "\\frac{}{}", tooltip: "分数", cursorOffset: -3 },
      { label: "√x", latex: "\\sqrt{}", tooltip: "平方根", cursorOffset: -1 },
      { label: "ⁿ√x", latex: "\\sqrt[]{}", tooltip: "n乗根", cursorOffset: -3 },
      { label: "(n k)", latex: "\\binom{}{}", tooltip: "二項係数", cursorOffset: -3 },
      { label: "x̄", latex: "\\overline{}", tooltip: "上線", cursorOffset: -1 },
      { label: "x_", latex: "\\underline{}", tooltip: "下線", cursorOffset: -1 }
    ]
  },
  {
    id: "large-ops",
    label: "大型演算子",
    icon: "∫",
    buttons: [
      { label: "∑", latex: "\\sum_{}^{}", tooltip: "総和", cursorOffset: -4, wide: true },
      { label: "∏", latex: "\\prod_{}^{}", tooltip: "総乗", cursorOffset: -4, wide: true },
      { label: "∐", latex: "\\coprod_{}^{}", tooltip: "余積", cursorOffset: -4, wide: true },
      { label: "∫", latex: "\\int_{}^{}", tooltip: "積分", cursorOffset: -4, wide: true },
      { label: "∬", latex: "\\iint", tooltip: "二重積分", wide: true },
      { label: "∭", latex: "\\iiint", tooltip: "三重積分", wide: true },
      { label: "∮", latex: "\\oint", tooltip: "周回積分", wide: true },
      { label: "lim", latex: "\\lim_{}", tooltip: "極限", cursorOffset: -1, wide: true },
      { label: "⋃", latex: "\\bigcup_{}^{}", tooltip: "和集合", cursorOffset: -4, wide: true },
      { label: "⋂", latex: "\\bigcap_{}^{}", tooltip: "積集合", cursorOffset: -4, wide: true }
    ]
  },
  {
    id: "matrices",
    label: "行列",
    icon: "[ ]",
    buttons: [
      { label: "( ) 2×2", latex: "\\begin{pmatrix}\n & \\\\\n & \n\\end{pmatrix}", tooltip: "丸括弧行列 2x2", wide: true },
      { label: "( ) 3×3", latex: "\\begin{pmatrix}\n & & \\\\\n & & \\\\\n & & \n\\end{pmatrix}", tooltip: "丸括弧行列 3x3", wide: true },
      { label: "[ ] 2×2", latex: "\\begin{bmatrix}\n & \\\\\n & \n\\end{bmatrix}", tooltip: "角括弧行列 2x2", wide: true },
      { label: "[ ] 3×3", latex: "\\begin{bmatrix}\n & & \\\\\n & & \\\\\n & & \n\\end{bmatrix}", tooltip: "角括弧行列 3x3", wide: true },
      { label: "| | 2×2", latex: "\\begin{vmatrix}\n & \\\\\n & \n\\end{vmatrix}", tooltip: "行列式 2x2", wide: true },
      { label: "| | 3×3", latex: "\\begin{vmatrix}\n & & \\\\\n & & \\\\\n & & \n\\end{vmatrix}", tooltip: "行列式 3x3", wide: true },
      { label: "plain 2×2", latex: "\\begin{matrix}\n & \\\\\n & \n\\end{matrix}", tooltip: "括弧なし行列 2x2", wide: true },
      { label: "cases", latex: "\\begin{cases}\n & \\\\\n & \n\\end{cases}", tooltip: "場合分け", wide: true },
      { label: "aligned", latex: "\\begin{aligned}\n & = \\\\\n & = \n\\end{aligned}", tooltip: "整列 (aligned)", wide: true }
    ]
  },
  {
    id: "brackets",
    label: "括弧",
    icon: "()",
    buttons: [
      { label: "( )", latex: "\\left( \\right)", tooltip: "丸括弧", cursorOffset: -7 },
      { label: "[ ]", latex: "\\left[ \\right]", tooltip: "角括弧", cursorOffset: -7 },
      { label: "{ }", latex: "\\left\\{ \\right\\}", tooltip: "波括弧", cursorOffset: -9 },
      { label: "⟨ ⟩", latex: "\\left\\langle \\right\\rangle", tooltip: "山括弧", cursorOffset: -14 },
      { label: "| |", latex: "\\left| \\right|", tooltip: "絶対値", cursorOffset: -7 },
      { label: "‖ ‖", latex: "\\left\\| \\right\\|", tooltip: "ノルム", cursorOffset: -9 },
      { label: "⌈ ⌉", latex: "\\left\\lceil \\right\\rceil", tooltip: "天井関数", cursorOffset: -13 },
      { label: "⌊ ⌋", latex: "\\left\\lfloor \\right\\rfloor", tooltip: "床関数", cursorOffset: -14 }
    ]
  },
  {
    id: "arrows",
    label: "矢印",
    icon: "→",
    buttons: [
      { label: "→", latex: "\\rightarrow", tooltip: "右矢印" },
      { label: "←", latex: "\\leftarrow", tooltip: "左矢印" },
      { label: "↔", latex: "\\leftrightarrow", tooltip: "左右矢印" },
      { label: "⇒", latex: "\\Rightarrow", tooltip: "右二重矢印" },
      { label: "⇐", latex: "\\Leftarrow", tooltip: "左二重矢印" },
      { label: "⇔", latex: "\\Leftrightarrow", tooltip: "左右二重矢印" },
      { label: "↦", latex: "\\mapsto", tooltip: "写像" },
      { label: "⟹", latex: "\\implies", tooltip: "ならば" },
      { label: "⟺", latex: "\\iff", tooltip: "同値" },
      { label: "↑", latex: "\\uparrow", tooltip: "上矢印" },
      { label: "↓", latex: "\\downarrow", tooltip: "下矢印" },
      { label: "⇑", latex: "\\Uparrow", tooltip: "上二重矢印" },
      { label: "⇓", latex: "\\Downarrow", tooltip: "下二重矢印" },
      { label: "↗", latex: "\\nearrow", tooltip: "右上矢印" },
      { label: "↘", latex: "\\searrow", tooltip: "右下矢印" }
    ]
  },
  {
    id: "functions",
    label: "関数",
    icon: "sin",
    buttons: [
      { label: "sin", latex: "\\sin", tooltip: "サイン", wide: true },
      { label: "cos", latex: "\\cos", tooltip: "コサイン", wide: true },
      { label: "tan", latex: "\\tan", tooltip: "タンジェント", wide: true },
      { label: "sec", latex: "\\sec", tooltip: "セカント", wide: true },
      { label: "csc", latex: "\\csc", tooltip: "コセカント", wide: true },
      { label: "cot", latex: "\\cot", tooltip: "コタンジェント", wide: true },
      { label: "arcsin", latex: "\\arcsin", tooltip: "アークサイン", wide: true },
      { label: "arccos", latex: "\\arccos", tooltip: "アークコサイン", wide: true },
      { label: "arctan", latex: "\\arctan", tooltip: "アークタンジェント", wide: true },
      { label: "sinh", latex: "\\sinh", tooltip: "双曲線サイン", wide: true },
      { label: "cosh", latex: "\\cosh", tooltip: "双曲線コサイン", wide: true },
      { label: "tanh", latex: "\\tanh", tooltip: "双曲線タンジェント", wide: true },
      { label: "log", latex: "\\log", tooltip: "対数", wide: true },
      { label: "ln", latex: "\\ln", tooltip: "自然対数", wide: true },
      { label: "exp", latex: "\\exp", tooltip: "指数", wide: true },
      { label: "lim", latex: "\\lim", tooltip: "極限", wide: true },
      { label: "min", latex: "\\min", tooltip: "最小値", wide: true },
      { label: "max", latex: "\\max", tooltip: "最大値", wide: true },
      { label: "det", latex: "\\det", tooltip: "行列式", wide: true },
      { label: "gcd", latex: "\\gcd", tooltip: "最大公約数", wide: true },
      { label: "inf", latex: "\\inf", tooltip: "下限", wide: true },
      { label: "sup", latex: "\\sup", tooltip: "上限", wide: true },
      { label: "dim", latex: "\\dim", tooltip: "次元", wide: true },
      { label: "ker", latex: "\\ker", tooltip: "核", wide: true }
    ]
  },
  {
    id: "accents",
    label: "装飾",
    icon: "x̂",
    buttons: [
      { label: "x̂", latex: "\\hat{}", tooltip: "ハット", cursorOffset: -1 },
      { label: "x̌", latex: "\\check{}", tooltip: "チェック", cursorOffset: -1 },
      { label: "x̄", latex: "\\bar{}", tooltip: "バー", cursorOffset: -1 },
      { label: "ẋ", latex: "\\dot{}", tooltip: "ドット", cursorOffset: -1 },
      { label: "ẍ", latex: "\\ddot{}", tooltip: "ダブルドット", cursorOffset: -1 },
      { label: "x⃗", latex: "\\vec{}", tooltip: "ベクトル", cursorOffset: -1 },
      { label: "x̃", latex: "\\tilde{}", tooltip: "チルダ", cursorOffset: -1 },
      { label: "x˘", latex: "\\breve{}", tooltip: "ブレーヴ", cursorOffset: -1 },
      { label: "x́", latex: "\\acute{}", tooltip: "アキュート", cursorOffset: -1 },
      { label: "x̀", latex: "\\grave{}", tooltip: "グレイヴ", cursorOffset: -1 },
      { label: "⏞x", latex: "\\overbrace{}", tooltip: "上波括弧", cursorOffset: -1 },
      { label: "⏟x", latex: "\\underbrace{}", tooltip: "下波括弧", cursorOffset: -1 },
      { label: "→x", latex: "\\overrightarrow{}", tooltip: "上矢印", cursorOffset: -1 },
      { label: "←x", latex: "\\overleftarrow{}", tooltip: "上左矢印", cursorOffset: -1 },
      { label: "x̂ₘ", latex: "\\widehat{}", tooltip: "ワイドハット", cursorOffset: -1 },
      { label: "x̃ₘ", latex: "\\widetilde{}", tooltip: "ワイドチルダ", cursorOffset: -1 }
    ]
  },
  {
    id: "formatting",
    label: "書式",
    icon: "Aa",
    buttons: [
      { label: "文字色", action: "textcolor", tooltip: "文字色", wide: true },
      { label: "背景色", action: "bgcolor", tooltip: "背景色", wide: true },
      { label: "取消線 ╱", latex: "\\cancel{}", tooltip: "取消線 (左下→右上)", cursorOffset: -1, wide: true, wrap: true },
      { label: "取消線 ╲", latex: "\\bcancel{}", tooltip: "逆取消線 (左上→右下)", cursorOffset: -1, wide: true, wrap: true },
      { label: "取消線 ╳", latex: "\\xcancel{}", tooltip: "×取消線", cursorOffset: -1, wide: true, wrap: true },
      { label: "囲み枠", latex: "\\boxed{}", tooltip: "囲み枠", cursorOffset: -1, wide: true, wrap: true }
    ]
  },
  {
    id: "misc",
    label: "その他",
    icon: "∞",
    buttons: [
      { label: "∞", latex: "\\infty", tooltip: "無限大" },
      { label: "∂", latex: "\\partial", tooltip: "偏微分" },
      { label: "∇", latex: "\\nabla", tooltip: "ナブラ" },
      { label: "∅", latex: "\\emptyset", tooltip: "空集合" },
      { label: "∀", latex: "\\forall", tooltip: "全称" },
      { label: "∃", latex: "\\exists", tooltip: "存在" },
      { label: "¬", latex: "\\neg", tooltip: "否定" },
      { label: "∧", latex: "\\land", tooltip: "論理積 (AND)" },
      { label: "∨", latex: "\\lor", tooltip: "論理和 (OR)" },
      { label: "⊥", latex: "\\perp", tooltip: "直交" },
      { label: "∠", latex: "\\angle", tooltip: "角度" },
      { label: "△", latex: "\\triangle", tooltip: "三角形" },
      { label: "□", latex: "\\square", tooltip: "四角形" },
      { label: "ℝ", latex: "\\mathbb{R}", tooltip: "実数" },
      { label: "ℤ", latex: "\\mathbb{Z}", tooltip: "整数" },
      { label: "ℕ", latex: "\\mathbb{N}", tooltip: "自然数" },
      { label: "ℂ", latex: "\\mathbb{C}", tooltip: "複素数" },
      { label: "ℚ", latex: "\\mathbb{Q}", tooltip: "有理数" },
      { label: "…", latex: "\\dots", tooltip: "ドット (水平)" },
      { label: "⋯", latex: "\\cdots", tooltip: "ドット (中央)" },
      { label: "⋮", latex: "\\vdots", tooltip: "ドット (垂直)" },
      { label: "⋱", latex: "\\ddots", tooltip: "ドット (斜め)" },
      { label: "スペース", latex: "\\quad", tooltip: "スペース (広)", wide: true },
      { label: "狭スペース", latex: "\\,", tooltip: "スペース (狭)", wide: true },
      { label: "テキスト", latex: "\\text{}", tooltip: "テキストモード", cursorOffset: -1, wide: true },
      { label: "太字", latex: "\\mathbf{}", tooltip: "太字", cursorOffset: -1, wide: true },
      { label: "斜体", latex: "\\mathit{}", tooltip: "斜体", cursorOffset: -1, wide: true },
      { label: "カリグラフィ", latex: "\\mathcal{}", tooltip: "カリグラフィ体", cursorOffset: -1, wide: true }
    ]
  }
];
